################################################################ manager

################################ basic

[[manager.prepend_keymap]]
on = ["g"]
run = "arrow top"

[[manager.prepend_keymap]]
on = ["<c-o>"]
run = "back"
[[manager.prepend_keymap]]
on = ["<c-i>"]
run = "forward"

[[manager.prepend_keymap]]
on = ["<down>"]
run = ["toggle", "arrow 1"]
[[manager.prepend_keymap]]
on = ["<up>"]
run = ["toggle", "arrow -1"]

[[manager.prepend_keymap]]
on = ["<s-esc>"]
run = "quit"
[[manager.prepend_keymap]]
on = ["<a-f>"]
run = "quit"

[[manager.prepend_keymap]]
on = ["d"]
run = "yank --cut"
[[manager.prepend_keymap]]
on = ["<c-g>"]
run = "unyank"

[[manager.prepend_keymap]]
on = ["x"]
run = "remove"
[[manager.prepend_keymap]]
on = ["X"]
run = "remove --permanently"

[[manager.prepend_keymap]]
on = ["A"]
run = "create --dir"

################################ shell

[[manager.prepend_keymap]]
on   = "<a-o>"
run  = """
shell ''
"""
desc = "test"

[[manager.prepend_keymap]]
on = ["<a-enter>"]
run = """
shell 'setsid -f $TERMINAL >/dev/null 2>&1'
"""
[[manager.prepend_keymap]]
on = ["<enter>"]
run = """
shell 'setsid -f $TERMINAL >/dev/null 2>&1'
"""

[[manager.prepend_keymap]]
on = ["<home>"]
run = """
shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
"""

[[manager.prepend_keymap]]
on   = "<a-x>"
run  = """
shell --block 'yazi-execute "$0" "$@"'
"""

[[manager.prepend_keymap]]
on   = "O"
run  = """
shell 'open-with-program "$@"'
"""

################################ plugin

[[manager.prepend_keymap]]
on = ["<pagedown>"]
run = "plugin parent-arrow --args=1"
[[manager.prepend_keymap]]
on = ["<pageup>"]
run = "plugin parent-arrow --args=-1"

[[manager.prepend_keymap]]
on = ["e"]
run = "plugin zoxide"

[[manager.prepend_keymap]]
on = ["i"]
run = "plugin fzf"

[[manager.prepend_keymap]]
on   = "<a-d>"
run  = "plugin diff"

################################################################ input

[[input.prepend_keymap]]
on   = ["<esc>"]
run  = "close"
